top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/mappers
builddir     = /root/httpd-2.4.51/modules/mappers
VPATH        = /root/httpd-2.4.51/modules/mappers

include $(top_srcdir)/build/special.mk

