top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/metadata
builddir     = /root/httpd-2.4.51/modules/metadata
VPATH        = /root/httpd-2.4.51/modules/metadata

include $(top_srcdir)/build/special.mk

