top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/loggers
builddir     = /root/httpd-2.4.51/modules/loggers
VPATH        = /root/httpd-2.4.51/modules/loggers

include $(top_srcdir)/build/special.mk

