top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/generators
builddir     = /root/httpd-2.4.51/modules/generators
VPATH        = /root/httpd-2.4.51/modules/generators

include $(top_srcdir)/build/special.mk

