top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/echo
builddir     = /root/httpd-2.4.51/modules/echo
VPATH        = /root/httpd-2.4.51/modules/echo

include $(top_srcdir)/build/special.mk

