top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/filters
builddir     = /root/httpd-2.4.51/modules/filters
VPATH        = /root/httpd-2.4.51/modules/filters

include $(top_srcdir)/build/special.mk

