top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/aaa
builddir     = /root/httpd-2.4.51/modules/aaa
VPATH        = /root/httpd-2.4.51/modules/aaa

include $(top_srcdir)/build/special.mk

