top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/server/mpm/event
builddir     = /root/httpd-2.4.51/server/mpm/event
VPATH        = /root/httpd-2.4.51/server/mpm/event
include $(top_srcdir)/build/special.mk
