top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/os
builddir     = /root/httpd-2.4.51/os
VPATH        = /root/httpd-2.4.51/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
