top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/srclib
builddir     = /root/httpd-2.4.51/srclib
VPATH        = /root/httpd-2.4.51/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
