top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/slotmem
builddir     = /root/httpd-2.4.51/modules/slotmem
VPATH        = /root/httpd-2.4.51/modules/slotmem
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
