top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/core
builddir     = /root/httpd-2.4.51/modules/core
VPATH        = /root/httpd-2.4.51/modules/core

include $(top_srcdir)/build/special.mk

