top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/modules/http
builddir     = /root/httpd-2.4.51/modules/http
VPATH        = /root/httpd-2.4.51/modules/http

include $(top_srcdir)/build/special.mk

