top_srcdir   = /root/httpd-2.4.51
top_builddir = /root/httpd-2.4.51
srcdir       = /root/httpd-2.4.51/server/mpm
builddir     = /root/httpd-2.4.51/server/mpm
VPATH        = /root/httpd-2.4.51/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
